
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 28 10:55:40 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 4;
  public static final int EOFILE = 10;
  public static final int SEMI = 6;
  public static final int EQUAL = 12;
  public static final int EOF = 0;
  public static final int STRING = 5;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int SPACE = 9;
  public static final int NEWLINE = 11;
  public static final int CHAR = 2;
  public static final int FLOAT = 3;
}

