
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 10 11:59:43 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 2;
  public static final int SEMI = 16;
  public static final int DECIMAL = 15;
  public static final int FL = 18;
  public static final int NIL = 12;
  public static final int ID = 5;
  public static final int SPACE = 6;
  public static final int NUM = 17;
  public static final int ST = 19;
  public static final int QUOTE = 10;
  public static final int STRING = 3;
  public static final int COMMA = 4;
  public static final int FLOAT = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int EOFILE = 7;
  public static final int STR = 11;
  public static final int NL = 8;
  public static final int VAR = 13;
}

